# Generated by Django 5.1.13 on 2025-12-08 07:15

import django.db.models.deletion
import django.utils.timezone
import django_currentuser.db.models.fields
import django_currentuser.middleware
import ticket.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique id')),
                ('_created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('_updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.CharField(blank=True, choices=[('technical', 'Technical'), ('order', 'Order'), ('question', 'Question'), ('others', 'Others')], max_length=30, null=True, verbose_name='category')),
                ('number', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='number')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='title')),
                ('status', models.CharField(blank=True, choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=30, null=True, verbose_name='status')),
                ('is_resolved', models.BooleanField(default=False)),
                ('can_reply', models.BooleanField(default=True)),
                ('can_upload_attachment', models.BooleanField(default=True)),
                ('type', models.CharField(blank=True, choices=[('user', 'User'), ('system', 'System'), ('admin', 'Admin')], max_length=30, null=True, verbose_name='type')),
                ('order', models.CharField(blank=True, max_length=150, null=True, verbose_name='order')),
                ('_created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='reviewer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Tickets',
                'verbose_name_plural': 'Ticket',
            },
        ),
        migrations.CreateModel(
            name='TicketDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique id')),
                ('_created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('_updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('content', models.CharField(blank=True, max_length=1500, null=True, verbose_name='content')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=ticket.models.ticket_attachment_path)),
                ('_created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='ticket.ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_detail_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'ticket_detail',
                'verbose_name_plural': 'ticket_details',
                'db_table': 'ticket_detail',
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['id'], name='ticket_tick_id_73761c_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketdetail',
            index=models.Index(fields=['id'], name='ticket_deta_id_1cfec4_idx'),
        ),
    ]
