# Generated by Django 5.1.15 on 2025-12-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_remove_ticket_category_remove_ticket_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='content'),
        ),
    ]
