# Generated by Django 5.1.15 on 2025-12-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticketmessage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdetail',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='ticketdetail',
            name='sender',
        ),
    ]
