# Generated by Django 5.1.15 on 2025-12-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_remove_ticketdetail_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdetail',
            name='message',
        ),
        migrations.AddField(
            model_name='ticketdetail',
            name='message',
            field=models.ManyToManyField(blank=True, related_name='ticket_details', to='ticket.ticketmessage', verbose_name='messages'),
        ),
    ]
