# Generated by Django 5.1.15 on 2025-12-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_remove_ticketdetail_message_ticketdetail_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='type',
        ),
    ]
