# Generated by Django 5.1.15 on 2025-12-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_remove_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('high', 'High'), ('force', 'Force')], max_length=400, null=True, verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(blank=True, choices=[('chat', 'Chat'), ('ticket', 'Ticket')], max_length=400, null=True, verbose_name='type'),
        ),
    ]
