# Generated by Django 5.1.15 on 2025-12-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_ticket_priority_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='order'),
        ),
    ]
