# Generated by Django 5.1.15 on 2025-12-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_ticket_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': '3-ticket', 'verbose_name_plural': '3-tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketdetail',
            options={'verbose_name': '4-ticket_detail', 'verbose_name_plural': '4-ticket_details'},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'verbose_name': '2-ticket_message', 'verbose_name_plural': '2-ticket_messages'},
        ),
        migrations.AlterModelOptions(
            name='ticketusergroup',
            options={'verbose_name': '1-ticket_user_group', 'verbose_name_plural': '1-ticket_user_groups'},
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='ticket_id_72dc5c_idx',
            old_name='ticket_tick_id_73761c_idx',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
        migrations.AlterModelTable(
            name='ticketusergroup',
            table='ticket_user_group',
        ),
    ]
