# Generated by Django 5.1.15 on 2025-12-29 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_alter_ticket_options_alter_ticketdetail_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='users_group',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ManyToManyField(related_name='ticket_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
