# Generated by Django 5.1.15 on 2025-12-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_remove_ticket_users_group_remove_ticket_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdetail',
            name='user',
        ),
    ]
