# Generated by Django 5.1.15 on 2025-12-30 06:21

import ticket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_remove_ticketdetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdetail',
            name='message',
        ),
        migrations.RemoveField(
            model_name='ticketusergroup',
            name='_created_by',
        ),
        migrations.RemoveField(
            model_name='ticketusergroup',
            name='_updated_by',
        ),
        migrations.RemoveField(
            model_name='ticketusergroup',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='ticketusergroup',
            name='members',
        ),
        migrations.AddField(
            model_name='ticketdetail',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=ticket.models.ticket_attachment_path, validators=[ticket.models.validate_attachment_file]),
        ),
        migrations.DeleteModel(
            name='TicketMessage',
        ),
        migrations.AddField(
            model_name='ticketdetail',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='message'),
        ),
        migrations.DeleteModel(
            name='TicketUserGroup',
        ),
    ]
